import type { Metadata } from "next";
import { Montserrat , Zen_Kaku_Gothic_New } from "next/font/google";
import "./globals.css";
import Header from "./component/layouts/header/Header";

const geistSans = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Zen_Kaku_Gothic_New({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight:"400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
